#!/usr/bin/env python3
"""
Regenerate build/step5_species_info.inc and build/step5_national_dex.inc
from tools/step5_cache/ CSV data.

Run from repo root:
  python3 tools/gen_step5_species_inc.py
"""

import csv, os

CACHE = "tools/step5_cache"

TYPE_MAP = {
    1:"TYPE_NORMAL", 2:"TYPE_FIGHTING", 3:"TYPE_FLYING", 4:"TYPE_POISON",
    5:"TYPE_GROUND", 6:"TYPE_ROCK", 7:"TYPE_BUG", 8:"TYPE_GHOST",
    9:"TYPE_STEEL", 10:"TYPE_FIRE", 11:"TYPE_WATER", 12:"TYPE_GRASS",
    13:"TYPE_ELECTRIC", 14:"TYPE_PSYCHIC", 15:"TYPE_ICE", 16:"TYPE_DRAGON",
    17:"TYPE_DARK", 18:"TYPE_FAIRY",
}
GROWTH_MAP = {
    1:"GROWTH_SLOW", 2:"GROWTH_MEDIUM_FAST", 3:"GROWTH_FAST",
    4:"GROWTH_MEDIUM_SLOW", 5:"GROWTH_ERRATIC", 6:"GROWTH_FLUCTUATING",
}
GENDER_MAP = {
    -1:"MON_GENDERLESS", 0:"PERCENT_FEMALE(0)", 1:"PERCENT_FEMALE(12)",
    2:"PERCENT_FEMALE(25)", 4:"PERCENT_FEMALE(50)", 6:"PERCENT_FEMALE(75)",
    7:"PERCENT_FEMALE(87)", 8:"PERCENT_FEMALE(100)",
}

# (ab1, ab2, body_color, exp_yield, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef)
CORRECTIONS = {
    "SPECIES_SHINX":               ("ABILITY_STATIC",      "ABILITY_INTIMIDATE",  "BODY_COLOR_BLUE",   64,  0,0,0,1,0,0),
    "SPECIES_AXEW":                ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_GREEN",  64,  0,1,0,0,0,0),
    "SPECIES_HONEDGE":             ("ABILITY_BATTLE_ARMOR","ABILITY_NONE",        "BODY_COLOR_BLUE",   65,  0,0,1,0,0,0),
    "SPECIES_GALARIAN_ZIGZAGOON":  ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_WHITE",  56,  0,0,0,1,0,0),
    "SPECIES_LUXIO":               ("ABILITY_STATIC",      "ABILITY_INTIMIDATE",  "BODY_COLOR_BLUE",  127,  0,0,0,0,0,2),
    "SPECIES_LUXRAY":              ("ABILITY_INTIMIDATE",  "ABILITY_STATIC",      "BODY_COLOR_BLUE",  216,  0,0,0,0,0,3),
    "SPECIES_FRAXURE":             ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_GREEN", 144,  0,2,0,0,0,0),
    "SPECIES_HAXORUS":             ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_GREEN", 243,  0,3,0,0,0,0),
    "SPECIES_DOUBLADE":            ("ABILITY_BATTLE_ARMOR","ABILITY_NONE",        "BODY_COLOR_GRAY",  157,  0,0,2,0,0,0),
    "SPECIES_AEGISLASH":           ("ABILITY_SHELL_ARMOR", "ABILITY_NONE",        "BODY_COLOR_YELLOW",234,  0,0,3,0,0,0),
    "SPECIES_GALARIAN_LINOONE":    ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_WHITE", 147,  0,0,0,2,0,0),
    "SPECIES_OBSTAGOON":           ("ABILITY_GUTS",        "ABILITY_NONE",        "BODY_COLOR_WHITE", 261,  0,3,0,0,0,0),
    "SPECIES_STARLY":              ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_BROWN",  49,  0,0,0,1,0,0),
    "SPECIES_STARAVIA":            ("ABILITY_INTIMIDATE",  "ABILITY_NONE",        "BODY_COLOR_BROWN", 119,  0,0,0,2,0,0),
    "SPECIES_STARAPTOR":           ("ABILITY_INTIMIDATE",  "ABILITY_NONE",        "BODY_COLOR_BROWN", 218,  0,3,0,0,0,0),
    "SPECIES_MUNCHLAX":            ("ABILITY_PICKUP",      "ABILITY_THICK_FAT",   "BODY_COLOR_BLUE",   78,  1,0,0,0,0,0),
    "SPECIES_PORYGON_Z":           ("ABILITY_TRACE",       "ABILITY_NONE",        "BODY_COLOR_PINK",  241,  0,0,0,0,3,0),
    "SPECIES_HISUIAN_ZORUA":       ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_WHITE",  66,  0,0,0,0,1,0),
    "SPECIES_HISUIAN_ZOROARK":     ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_WHITE", 179,  0,0,0,0,2,0),
    "SPECIES_FLETCHLING":          ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_RED",    56,  0,0,0,1,0,0),
    "SPECIES_FLETCHINDER":         ("ABILITY_FLAME_BODY",  "ABILITY_NONE",        "BODY_COLOR_RED",   128,  0,0,0,2,0,0),
    "SPECIES_TALONFLAME":          ("ABILITY_FLAME_BODY",  "ABILITY_NONE",        "BODY_COLOR_RED",   175,  0,0,0,3,0,0),
    "SPECIES_URSALUNA":            ("ABILITY_GUTS",        "ABILITY_NONE",        "BODY_COLOR_BROWN", 243,  3,0,0,0,0,0),
    "SPECIES_SALANDIT":            ("ABILITY_OBLIVIOUS",   "ABILITY_NONE",        "BODY_COLOR_GRAY",   64,  0,0,0,1,0,0),
    "SPECIES_SALAZZLE":            ("ABILITY_OBLIVIOUS",   "ABILITY_NONE",        "BODY_COLOR_PURPLE",168,  0,0,0,2,0,0),
    "SPECIES_LITWICK":             ("ABILITY_FLASH_FIRE",  "ABILITY_FLAME_BODY",  "BODY_COLOR_YELLOW", 55,  0,0,0,0,1,0),
    "SPECIES_LAMPENT":             ("ABILITY_FLASH_FIRE",  "ABILITY_FLAME_BODY",  "BODY_COLOR_GRAY",  130,  0,0,0,0,2,0),
    "SPECIES_CHANDELURE":          ("ABILITY_FLASH_FIRE",  "ABILITY_FLAME_BODY",  "BODY_COLOR_PURPLE",234,  0,0,0,0,3,0),
    "SPECIES_CHIMCHAR":            ("ABILITY_BLAZE",       "ABILITY_NONE",        "BODY_COLOR_RED",    62,  0,0,0,1,0,0),
    "SPECIES_MONFERNO":            ("ABILITY_BLAZE",       "ABILITY_NONE",        "BODY_COLOR_RED",   142,  0,0,0,2,0,0),
    "SPECIES_INFERNAPE":           ("ABILITY_BLAZE",       "ABILITY_NONE",        "BODY_COLOR_RED",   240,  0,0,0,3,0,0),
    "SPECIES_PIPLUP":              ("ABILITY_TORRENT",     "ABILITY_NONE",        "BODY_COLOR_BLUE",   63,  0,0,0,0,0,1),
    "SPECIES_PRINPLUP":            ("ABILITY_TORRENT",     "ABILITY_NONE",        "BODY_COLOR_BLUE",  142,  0,0,0,0,0,2),
    "SPECIES_EMPOLEON":            ("ABILITY_TORRENT",     "ABILITY_KEEN_EYE",    "BODY_COLOR_BLUE",  239,  0,0,0,0,3,0),
    "SPECIES_BUIZEL":              ("ABILITY_SWIFT_SWIM",  "ABILITY_NONE",        "BODY_COLOR_YELLOW", 66,  0,0,0,1,0,0),
    "SPECIES_FLOATZEL":            ("ABILITY_SWIFT_SWIM",  "ABILITY_NONE",        "BODY_COLOR_YELLOW",173,  0,0,0,2,0,0),
    "SPECIES_MAGMORTAR":           ("ABILITY_FLAME_BODY",  "ABILITY_VITAL_SPIRIT","BODY_COLOR_RED",   243,  0,0,0,0,3,0),
    "SPECIES_ELECTIVIRE":          ("ABILITY_STATIC",      "ABILITY_VITAL_SPIRIT","BODY_COLOR_YELLOW",243,  0,3,0,0,0,0),
    "SPECIES_ROTOM":               ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_RED",   182,  0,0,0,0,1,0),
    "SPECIES_ROTOM_HEAT":          ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_RED",   182,  0,0,0,0,1,0),
    "SPECIES_ROTOM_WASH":          ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  182,  0,0,0,0,1,0),
    "SPECIES_ROTOM_FROST":         ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  182,  0,0,0,0,1,0),
    "SPECIES_ROTOM_FAN":           ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_RED",   182,  0,0,0,0,1,0),
    "SPECIES_ROTOM_MOW":           ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_GREEN", 182,  0,0,0,0,1,0),
    "SPECIES_TOXEL":               ("ABILITY_STATIC",      "ABILITY_NONE",        "BODY_COLOR_PURPLE", 48,  1,0,0,0,0,0),
    "SPECIES_TOXTRICITY":          ("ABILITY_PLUS",        "ABILITY_MINUS",       "BODY_COLOR_PURPLE",168,  0,0,0,0,2,0),
    "SPECIES_TYNAMO":              ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_WHITE",  55,  0,0,0,1,0,0),
    "SPECIES_EELEKTRIK":           ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  142,  0,0,0,0,2,0),
    "SPECIES_EELEKTROSS":          ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  232,  0,3,0,0,0,0),
    "SPECIES_ROSERADE":            ("ABILITY_NATURAL_CURE","ABILITY_POISON_POINT","BODY_COLOR_GREEN", 232,  0,0,0,0,3,0),
    "SPECIES_TANGROWTH":           ("ABILITY_CHLOROPHYLL", "ABILITY_NONE",        "BODY_COLOR_GREEN", 211,  0,0,2,0,0,0),
    "SPECIES_LEAFEON":             ("ABILITY_CHLOROPHYLL", "ABILITY_NONE",        "BODY_COLOR_GREEN", 184,  0,0,2,0,0,0),
    "SPECIES_GLACEON":             ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_BLUE",  184,  0,0,0,0,0,2),
    "SPECIES_SYLVEON":             ("ABILITY_CUTE_CHARM",  "ABILITY_NONE",        "BODY_COLOR_PINK",  184,  0,0,0,0,0,2),
    "SPECIES_FERROSEED":           ("ABILITY_ROUGH_SKIN",  "ABILITY_NONE",        "BODY_COLOR_GREEN",  61,  0,0,1,0,0,1),
    "SPECIES_FERROTHORN":          ("ABILITY_ROUGH_SKIN",  "ABILITY_NONE",        "BODY_COLOR_GREEN", 171,  0,0,2,0,0,1),
    "SPECIES_PUMPKABOO":           ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_BROWN",  67,  1,0,0,0,0,0),
    "SPECIES_GOURGEIST":           ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_BROWN", 173,  2,0,0,0,0,0),
    "SPECIES_PHANTUMP":            ("ABILITY_NATURAL_CURE","ABILITY_NONE",        "BODY_COLOR_BROWN",  62,  1,0,0,0,0,0),
    "SPECIES_TREVENANT":           ("ABILITY_NATURAL_CURE","ABILITY_NONE",        "BODY_COLOR_BROWN", 167,  2,0,0,0,0,0),
    "SPECIES_GALARIAN_MR_MIME":    ("ABILITY_SERENE_GRACE","ABILITY_NONE",        "BODY_COLOR_BLUE",  161,  0,0,0,1,0,0),
    "SPECIES_MR_RIME":             ("ABILITY_SERENE_GRACE","ABILITY_NONE",        "BODY_COLOR_WHITE", 207,  0,0,0,0,0,2),
    "SPECIES_MAMOSWINE":           ("ABILITY_OBLIVIOUS",   "ABILITY_NONE",        "BODY_COLOR_BROWN", 239,  0,3,0,0,0,0),
    "SPECIES_FROSLASS":            ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_WHITE", 168,  0,0,0,2,0,0),
    "SPECIES_WEAVILE":             ("ABILITY_PRESSURE",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 179,  0,1,0,1,0,0),
    "SPECIES_GALARIAN_DARUMAKA":   ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_WHITE", 115,  0,1,0,0,0,0),
    "SPECIES_GALARIAN_DARMANITAN": ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_WHITE", 168,  0,2,0,0,0,0),
    "SPECIES_ANNIHILAPE":          ("ABILITY_VITAL_SPIRIT","ABILITY_INNER_FOCUS", "BODY_COLOR_PURPLE",200,  0,3,0,0,0,0),
    "SPECIES_GALARIAN_FARFETCHD":  ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BROWN", 132,  0,1,0,0,0,0),
    "SPECIES_SIRFETCHD":           ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_WHITE", 221,  0,2,0,0,0,0),
    "SPECIES_PANCHAM":             ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_GRAY",   70,  0,1,0,0,0,0),
    "SPECIES_PANGORO":             ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLACK", 173,  0,2,0,0,0,0),
    "SPECIES_CROAGUNK":            ("ABILITY_POISON_POINT","ABILITY_NONE",        "BODY_COLOR_BLUE",   60,  0,1,0,0,0,0),
    "SPECIES_TOXICROAK":           ("ABILITY_POISON_POINT","ABILITY_NONE",        "BODY_COLOR_BLUE",  172,  0,2,0,0,0,0),
    "SPECIES_RIOLU":               ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLUE",   57,  0,1,0,0,0,0),
    "SPECIES_LUCARIO":             ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLUE",  184,  0,1,0,0,1,0),
    "SPECIES_SCRAGGY":             ("ABILITY_SHED_SKIN",   "ABILITY_NONE",        "BODY_COLOR_YELLOW", 70,  0,1,0,0,0,0),
    "SPECIES_SCRAFTY":             ("ABILITY_SHED_SKIN",   "ABILITY_NONE",        "BODY_COLOR_RED",   171,  0,1,1,0,0,0),
    "SPECIES_SKRELP":              ("ABILITY_POISON_POINT","ABILITY_NONE",        "BODY_COLOR_BROWN",  64,  0,0,0,0,0,1),
    "SPECIES_DRAGALGE":            ("ABILITY_POISON_POINT","ABILITY_NONE",        "BODY_COLOR_BROWN", 173,  0,0,0,0,0,2),
    "SPECIES_GIBLE":               ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_BLUE",   60,  0,1,0,0,0,0),
    "SPECIES_GABITE":              ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_BLUE",  144,  0,2,0,0,0,0),
    "SPECIES_GARCHOMP":            ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_BLUE",  270,  0,3,0,0,0,0),
    "SPECIES_GLISCOR":             ("ABILITY_HYPER_CUTTER","ABILITY_SAND_VEIL",   "BODY_COLOR_PURPLE",179,  0,0,2,0,0,0),
    "SPECIES_RHYPERIOR":           ("ABILITY_LIGHTNING_ROD","ABILITY_NONE",       "BODY_COLOR_BROWN", 241,  0,0,3,0,0,0),
    "SPECIES_DRILBUR":             ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_GRAY",   66,  0,1,0,0,0,0),
    "SPECIES_EXCADRILL":           ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_GRAY",  178,  0,2,1,0,0,0),
    "SPECIES_SANDILE":             ("ABILITY_INTIMIDATE",  "ABILITY_NONE",        "BODY_COLOR_BROWN",  58,  0,1,0,0,0,0),
    "SPECIES_KROKOROK":            ("ABILITY_INTIMIDATE",  "ABILITY_NONE",        "BODY_COLOR_BROWN", 123,  0,2,0,0,0,0),
    "SPECIES_KROOKODILE":          ("ABILITY_INTIMIDATE",  "ABILITY_NONE",        "BODY_COLOR_BROWN", 234,  0,3,0,0,0,0),
    "SPECIES_GOLETT":              ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_GREEN",  61,  1,0,0,0,0,0),
    "SPECIES_GOLURK":              ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_GREEN", 169,  0,3,0,0,0,0),
    "SPECIES_HONCHKROW":           ("ABILITY_INSOMNIA",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 177,  0,2,0,0,0,0),
    "SPECIES_TOGEKISS":            ("ABILITY_HUSTLE",      "ABILITY_SERENE_GRACE","BODY_COLOR_WHITE", 245,  0,0,0,0,3,0),
    "SPECIES_YANMEGA":             ("ABILITY_SPEED_BOOST", "ABILITY_NONE",        "BODY_COLOR_GREEN", 180,  0,0,0,0,2,0),
    "SPECIES_HAWLUCHA":            ("ABILITY_LIMBER",      "ABILITY_NONE",        "BODY_COLOR_GREEN", 175,  0,2,0,0,0,0),
    "SPECIES_ROOKIDEE":            ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",   49,  0,0,0,1,0,0),
    "SPECIES_CORVISQUIRE":         ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_GRAY",  124,  0,0,0,2,0,0),
    "SPECIES_CORVIKNIGHT":         ("ABILITY_PRESSURE",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 220,  0,0,3,0,0,0),
    "SPECIES_GALLADE":             ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_GREEN", 233,  0,3,0,0,0,0),
    "SPECIES_INKAY":               ("ABILITY_SUCTION_CUPS","ABILITY_NONE",        "BODY_COLOR_PURPLE", 58,  0,1,0,0,0,0),
    "SPECIES_MALAMAR":             ("ABILITY_SUCTION_CUPS","ABILITY_NONE",        "BODY_COLOR_PURPLE",169,  0,2,0,0,0,0),
    "SPECIES_LARVESTA":            ("ABILITY_FLAME_BODY",  "ABILITY_SWARM",       "BODY_COLOR_WHITE",  72,  0,0,0,0,2,0),
    "SPECIES_VOLCARONA":           ("ABILITY_FLAME_BODY",  "ABILITY_SWARM",       "BODY_COLOR_YELLOW",248,  0,0,0,0,3,0),
    "SPECIES_GRUBBIN":             ("ABILITY_SWARM",       "ABILITY_NONE",        "BODY_COLOR_YELLOW", 60,  1,0,0,0,0,0),
    "SPECIES_CHARJABUG":           ("ABILITY_PLUS",        "ABILITY_NONE",        "BODY_COLOR_GRAY",  130,  0,0,2,0,0,0),
    "SPECIES_VIKAVOLT":            ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_GREEN", 225,  0,0,0,0,3,0),
    "SPECIES_SIZZLIPEDE":          ("ABILITY_FLASH_FIRE",  "ABILITY_WHITE_SMOKE", "BODY_COLOR_RED",    56,  1,0,0,0,0,0),
    "SPECIES_CENTISKORCH":         ("ABILITY_FLASH_FIRE",  "ABILITY_WHITE_SMOKE", "BODY_COLOR_RED",   170,  0,0,0,0,3,0),
    "SPECIES_KLEAVOR":             ("ABILITY_SWARM",       "ABILITY_HUSTLE",      "BODY_COLOR_BROWN", 200,  0,2,0,0,0,0),
    "SPECIES_HISUIAN_GROWLITHE":   ("ABILITY_INTIMIDATE",  "ABILITY_FLASH_FIRE",  "BODY_COLOR_BROWN",  70,  0,1,0,0,0,0),
    "SPECIES_HISUIAN_ARCANINE":    ("ABILITY_INTIMIDATE",  "ABILITY_FLASH_FIRE",  "BODY_COLOR_BROWN", 194,  0,3,0,0,0,0),
    "SPECIES_ALOLAN_GEODUDE":      ("ABILITY_MAGNET_PULL", "ABILITY_STURDY",      "BODY_COLOR_GRAY",   60,  0,0,1,0,0,0),
    "SPECIES_ALOLAN_GRAVELER":     ("ABILITY_MAGNET_PULL", "ABILITY_STURDY",      "BODY_COLOR_GRAY",  137,  0,0,2,0,0,0),
    "SPECIES_ALOLAN_GOLEM":        ("ABILITY_MAGNET_PULL", "ABILITY_STURDY",      "BODY_COLOR_BROWN", 223,  0,0,3,0,0,0),
    "SPECIES_PROBOPASS":           ("ABILITY_MAGNET_PULL", "ABILITY_STURDY",      "BODY_COLOR_BROWN", 184,  1,0,0,0,0,2),
    "SPECIES_ROCKRUFF":            ("ABILITY_KEEN_EYE",    "ABILITY_VITAL_SPIRIT","BODY_COLOR_BROWN",  56,  0,1,0,0,0,0),
    "SPECIES_LYCANROC":            ("ABILITY_KEEN_EYE",    "ABILITY_SAND_VEIL",   "BODY_COLOR_BROWN", 170,  0,0,0,2,0,0),
    "SPECIES_DREEPY":              ("ABILITY_CLEAR_BODY",  "ABILITY_NONE",        "BODY_COLOR_BLUE",   54,  0,0,0,1,0,0),
    "SPECIES_DRAKLOAK":            ("ABILITY_CLEAR_BODY",  "ABILITY_NONE",        "BODY_COLOR_BLUE",  117,  0,0,0,2,0,0),
    "SPECIES_DRAGAPULT":           ("ABILITY_CLEAR_BODY",  "ABILITY_NONE",        "BODY_COLOR_BLUE",  300,  0,0,0,3,0,0),
    "SPECIES_BASCULIN":            ("ABILITY_ROCK_HEAD",   "ABILITY_NONE",        "BODY_COLOR_RED",   161,  0,0,0,2,0,0),
    "SPECIES_BASCULEGION":         ("ABILITY_SWIFT_SWIM",  "ABILITY_NONE",        "BODY_COLOR_WHITE", 216,  0,2,0,0,0,0),
    "SPECIES_ALOLAN_EXEGGUTOR":    ("ABILITY_ILLUMINATE",  "ABILITY_NONE",        "BODY_COLOR_GREEN", 186,  0,0,0,0,2,1),
    "SPECIES_DEINO":               ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_BLUE",   60,  0,0,0,0,1,0),
    "SPECIES_ZWEILOUS":            ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_PURPLE",147,  0,0,0,0,2,0),
    "SPECIES_HYDREIGON":           ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_PURPLE",270,  0,0,0,0,3,0),
    "SPECIES_GOOMY":               ("ABILITY_RAIN_DISH",   "ABILITY_NONE",        "BODY_COLOR_PURPLE", 60,  0,0,0,0,0,1),
    "SPECIES_SLIGGOO":             ("ABILITY_RAIN_DISH",   "ABILITY_NONE",        "BODY_COLOR_PURPLE",158,  0,0,0,0,0,2),
    "SPECIES_GOODRA":              ("ABILITY_RAIN_DISH",   "ABILITY_NONE",        "BODY_COLOR_PURPLE",270,  0,0,0,0,0,3),
    "SPECIES_DARKRAI":             ("ABILITY_INSOMNIA",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 270,  0,0,0,2,0,0),
    "SPECIES_ZORUA":               ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_BLACK",  66,  0,1,0,0,0,0),
    "SPECIES_ZOROARK":             ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 179,  0,2,0,0,0,0),
    "SPECIES_PAWNIARD":            ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLACK",  56,  0,1,0,0,0,0),
    "SPECIES_BISHARP":             ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLACK", 172,  0,2,0,0,0,0),
    "SPECIES_KINGAMBIT":           ("ABILITY_INNER_FOCUS", "ABILITY_NONE",        "BODY_COLOR_BLACK", 255,  0,3,0,0,0,0),
    "SPECIES_BRONZOR":             ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_GRAY",   60,  0,0,1,0,0,0),
    "SPECIES_BRONZONG":            ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_GRAY",  175,  0,0,2,0,0,0),
    "SPECIES_GALARIAN_MEOWTH":     ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_GRAY",   58,  0,1,0,0,0,0),
    "SPECIES_PERRSERKER":          ("ABILITY_BATTLE_ARMOR","ABILITY_NONE",        "BODY_COLOR_GRAY",  154,  0,2,0,0,0,0),
    "SPECIES_ALOLAN_MEOWTH":       ("ABILITY_PICKUP",      "ABILITY_NONE",        "BODY_COLOR_GRAY",   58,  0,0,0,1,0,0),
    "SPECIES_ALOLAN_PERSIAN":      ("ABILITY_KEEN_EYE",    "ABILITY_NONE",        "BODY_COLOR_GRAY",  154,  0,0,0,2,0,0),
    "SPECIES_DURALUDON":           ("ABILITY_CLEAR_BODY",  "ABILITY_NONE",        "BODY_COLOR_GRAY",  160,  0,0,0,0,2,0),
    "SPECIES_ARCHALUDON":          ("ABILITY_SHELL_ARMOR", "ABILITY_NONE",        "BODY_COLOR_GRAY",  227,  0,0,0,0,3,0),
    "SPECIES_TINKATINK":           ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_PINK",   60,  0,0,1,0,0,0),
    "SPECIES_TINKATUFF":           ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_PINK",  135,  0,0,2,0,0,0),
    "SPECIES_TINKATON":            ("ABILITY_HUSTLE",      "ABILITY_NONE",        "BODY_COLOR_PINK",  255,  0,0,3,0,0,0),
    "SPECIES_ALOLAN_DIGLETT":      ("ABILITY_SAND_VEIL",   "ABILITY_ARENA_TRAP",  "BODY_COLOR_BROWN",  53,  0,0,0,1,0,0),
    "SPECIES_ALOLAN_DUGTRIO":      ("ABILITY_SAND_VEIL",   "ABILITY_ARENA_TRAP",  "BODY_COLOR_BROWN", 149,  0,0,0,2,0,0),
    "SPECIES_MAGNEZONE":           ("ABILITY_MAGNET_PULL", "ABILITY_STURDY",      "BODY_COLOR_GRAY",  241,  0,0,0,0,3,0),
    "SPECIES_FLABEBE":             ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_WHITE",  61,  0,0,0,0,0,1),
    "SPECIES_FLOETTE":             ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_WHITE", 130,  0,0,0,0,0,2),
    "SPECIES_FLORGES":             ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_WHITE", 248,  0,0,0,0,0,3),
    "SPECIES_ALOLAN_VULPIX":       ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_WHITE",  60,  0,0,0,0,0,1),
    "SPECIES_ALOLAN_NINETALES":    ("ABILITY_SAND_VEIL",   "ABILITY_NONE",        "BODY_COLOR_WHITE", 179,  0,0,0,0,1,2),
    "SPECIES_UXIE":                ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_YELLOW",261,  0,0,0,0,0,2),
    "SPECIES_MESPRIT":             ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_PINK",  261,  0,0,0,0,2,0),
    "SPECIES_AZELF":               ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  261,  0,0,0,0,2,0),
    "SPECIES_DIALGA":              ("ABILITY_PRESSURE",    "ABILITY_NONE",        "BODY_COLOR_BLUE",  306,  0,0,0,0,3,0),
    "SPECIES_PALKIA":              ("ABILITY_PRESSURE",    "ABILITY_NONE",        "BODY_COLOR_PURPLE",306,  0,0,0,0,3,0),
    "SPECIES_HEATRAN":             ("ABILITY_FLASH_FIRE",  "ABILITY_FLAME_BODY",  "BODY_COLOR_RED",   270,  0,0,0,0,3,0),
    "SPECIES_REGIGIGAS":           ("ABILITY_TRUANT",      "ABILITY_NONE",        "BODY_COLOR_WHITE", 302,  0,3,0,0,0,0),
    "SPECIES_GIRATINA":            ("ABILITY_PRESSURE",    "ABILITY_NONE",        "BODY_COLOR_BLACK", 306,  3,0,0,0,0,0),
    "SPECIES_CRESSELIA":           ("ABILITY_LEVITATE",    "ABILITY_NONE",        "BODY_COLOR_YELLOW",270,  0,0,0,0,0,3),
    "SPECIES_PHIONE":              ("ABILITY_RAIN_DISH",   "ABILITY_NONE",        "BODY_COLOR_BLUE",  216,  1,0,0,0,0,0),
    "SPECIES_MANAPHY":             ("ABILITY_RAIN_DISH",   "ABILITY_NONE",        "BODY_COLOR_BLUE",  270,  3,0,0,0,0,0),
    "SPECIES_SHAYMIN":             ("ABILITY_NATURAL_CURE","ABILITY_SERENE_GRACE","BODY_COLOR_GREEN", 270,  3,0,0,0,0,0),
    "SPECIES_ARCEUS":              ("ABILITY_NONE",        "ABILITY_NONE",        "BODY_COLOR_WHITE", 324,  3,0,0,0,0,0),
}

# 164 Step-5 species: (FR_MACRO, pokeapi_identifier)
SPECIES_LIST = [
    ("SPECIES_LUXIO","luxio"), ("SPECIES_LUXRAY","luxray"),
    ("SPECIES_FRAXURE","fraxure"), ("SPECIES_HAXORUS","haxorus"),
    ("SPECIES_DOUBLADE","doublade"), ("SPECIES_AEGISLASH","aegislash-shield"),
    ("SPECIES_GALARIAN_LINOONE","linoone-galar"), ("SPECIES_OBSTAGOON","obstagoon"),
    ("SPECIES_STARLY","starly"), ("SPECIES_STARAVIA","staravia"), ("SPECIES_STARAPTOR","staraptor"),
    ("SPECIES_MUNCHLAX","munchlax"), ("SPECIES_PORYGON_Z","porygon-z"),
    ("SPECIES_HISUIAN_ZORUA","zorua-hisui"), ("SPECIES_HISUIAN_ZOROARK","zoroark-hisui"),
    ("SPECIES_FLETCHLING","fletchling"), ("SPECIES_FLETCHINDER","fletchinder"), ("SPECIES_TALONFLAME","talonflame"),
    ("SPECIES_URSALUNA","ursaluna"),
    ("SPECIES_SALANDIT","salandit"), ("SPECIES_SALAZZLE","salazzle"),
    ("SPECIES_LITWICK","litwick"), ("SPECIES_LAMPENT","lampent"), ("SPECIES_CHANDELURE","chandelure"),
    ("SPECIES_CHIMCHAR","chimchar"), ("SPECIES_MONFERNO","monferno"), ("SPECIES_INFERNAPE","infernape"),
    ("SPECIES_PIPLUP","piplup"), ("SPECIES_PRINPLUP","prinplup"), ("SPECIES_EMPOLEON","empoleon"),
    ("SPECIES_BUIZEL","buizel"), ("SPECIES_FLOATZEL","floatzel"),
    ("SPECIES_MAGMORTAR","magmortar"), ("SPECIES_ELECTIVIRE","electivire"),
    ("SPECIES_ROTOM","rotom"), ("SPECIES_ROTOM_HEAT","rotom-heat"), ("SPECIES_ROTOM_WASH","rotom-wash"),
    ("SPECIES_ROTOM_FROST","rotom-frost"), ("SPECIES_ROTOM_FAN","rotom-fan"), ("SPECIES_ROTOM_MOW","rotom-mow"),
    ("SPECIES_TOXEL","toxel"), ("SPECIES_TOXTRICITY","toxtricity"),
    ("SPECIES_TYNAMO","tynamo"), ("SPECIES_EELEKTRIK","eelektrik"), ("SPECIES_EELEKTROSS","eelektross"),
    ("SPECIES_ROSERADE","roserade"), ("SPECIES_TANGROWTH","tangrowth"),
    ("SPECIES_LEAFEON","leafeon"), ("SPECIES_GLACEON","glaceon"), ("SPECIES_SYLVEON","sylveon"),
    ("SPECIES_FERROSEED","ferroseed"), ("SPECIES_FERROTHORN","ferrothorn"),
    ("SPECIES_PUMPKABOO","pumpkaboo-average"), ("SPECIES_GOURGEIST","gourgeist-average"),
    ("SPECIES_PHANTUMP","phantump"), ("SPECIES_TREVENANT","trevenant"),
    ("SPECIES_GALARIAN_MR_MIME","mr-mime-galar"), ("SPECIES_MR_RIME","mr-rime"),
    ("SPECIES_MAMOSWINE","mamoswine"), ("SPECIES_FROSLASS","froslass"), ("SPECIES_WEAVILE","weavile"),
    ("SPECIES_GALARIAN_DARUMAKA","darumaka-galar"), ("SPECIES_GALARIAN_DARMANITAN","darmanitan-galar-standard"),
    ("SPECIES_ANNIHILAPE","annihilape"),
    ("SPECIES_GALARIAN_FARFETCHD","farfetchd-galar"), ("SPECIES_SIRFETCHD","sirfetchd"),
    ("SPECIES_PANCHAM","pancham"), ("SPECIES_PANGORO","pangoro"),
    ("SPECIES_CROAGUNK","croagunk"), ("SPECIES_TOXICROAK","toxicroak"),
    ("SPECIES_RIOLU","riolu"), ("SPECIES_LUCARIO","lucario"),
    ("SPECIES_SCRAGGY","scraggy"), ("SPECIES_SCRAFTY","scrafty"),
    ("SPECIES_SKRELP","skrelp"), ("SPECIES_DRAGALGE","dragalge"),
    ("SPECIES_GIBLE","gible"), ("SPECIES_GABITE","gabite"), ("SPECIES_GARCHOMP","garchomp"),
    ("SPECIES_GLISCOR","gliscor"), ("SPECIES_RHYPERIOR","rhyperior"),
    ("SPECIES_DRILBUR","drilbur"), ("SPECIES_EXCADRILL","excadrill"),
    ("SPECIES_SANDILE","sandile"), ("SPECIES_KROKOROK","krokorok"), ("SPECIES_KROOKODILE","krookodile"),
    ("SPECIES_GOLETT","golett"), ("SPECIES_GOLURK","golurk"),
    ("SPECIES_HONCHKROW","honchkrow"), ("SPECIES_TOGEKISS","togekiss"), ("SPECIES_YANMEGA","yanmega"),
    ("SPECIES_HAWLUCHA","hawlucha"),
    ("SPECIES_ROOKIDEE","rookidee"), ("SPECIES_CORVISQUIRE","corvisquire"), ("SPECIES_CORVIKNIGHT","corviknight"),
    ("SPECIES_GALLADE","gallade"),
    ("SPECIES_INKAY","inkay"), ("SPECIES_MALAMAR","malamar"),
    ("SPECIES_LARVESTA","larvesta"), ("SPECIES_VOLCARONA","volcarona"),
    ("SPECIES_GRUBBIN","grubbin"), ("SPECIES_CHARJABUG","charjabug"), ("SPECIES_VIKAVOLT","vikavolt"),
    ("SPECIES_SIZZLIPEDE","sizzlipede"), ("SPECIES_CENTISKORCH","centiskorch"),
    ("SPECIES_KLEAVOR","kleavor"),
    ("SPECIES_HISUIAN_GROWLITHE","growlithe-hisui"), ("SPECIES_HISUIAN_ARCANINE","arcanine-hisui"),
    ("SPECIES_ALOLAN_GEODUDE","geodude-alola"), ("SPECIES_ALOLAN_GRAVELER","graveler-alola"), ("SPECIES_ALOLAN_GOLEM","golem-alola"),
    ("SPECIES_PROBOPASS","probopass"),
    ("SPECIES_ROCKRUFF","rockruff"), ("SPECIES_LYCANROC","lycanroc-midday"),
    ("SPECIES_DREEPY","dreepy"), ("SPECIES_DRAKLOAK","drakloak"), ("SPECIES_DRAGAPULT","dragapult"),
    ("SPECIES_BASCULIN","basculin-red-striped"), ("SPECIES_BASCULEGION","basculegion"),
    ("SPECIES_ALOLAN_EXEGGUTOR","exeggutor-alola"),
    ("SPECIES_DEINO","deino"), ("SPECIES_ZWEILOUS","zweilous"), ("SPECIES_HYDREIGON","hydreigon"),
    ("SPECIES_GOOMY","goomy"), ("SPECIES_SLIGGOO","sliggoo"), ("SPECIES_GOODRA","goodra"),
    ("SPECIES_DARKRAI","darkrai"),
    ("SPECIES_ZORUA","zorua"), ("SPECIES_ZOROARK","zoroark"),
    ("SPECIES_PAWNIARD","pawniard"), ("SPECIES_BISHARP","bisharp"), ("SPECIES_KINGAMBIT","kingambit"),
    ("SPECIES_BRONZOR","bronzor"), ("SPECIES_BRONZONG","bronzong"),
    ("SPECIES_GALARIAN_MEOWTH","meowth-galar"), ("SPECIES_PERRSERKER","perrserker"),
    ("SPECIES_ALOLAN_MEOWTH","meowth-alola"), ("SPECIES_ALOLAN_PERSIAN","persian-alola"),
    ("SPECIES_DURALUDON","duraludon"), ("SPECIES_ARCHALUDON","archaludon"),
    ("SPECIES_TINKATINK","tinkatink"), ("SPECIES_TINKATUFF","tinkatuff"), ("SPECIES_TINKATON","tinkaton"),
    ("SPECIES_ALOLAN_DIGLETT","diglett-alola"), ("SPECIES_ALOLAN_DUGTRIO","dugtrio-alola"),
    ("SPECIES_MAGNEZONE","magnezone"),
    ("SPECIES_FLABEBE","flabebe"), ("SPECIES_FLOETTE","floette"), ("SPECIES_FLORGES","florges"),
    ("SPECIES_ALOLAN_VULPIX","vulpix-alola"), ("SPECIES_ALOLAN_NINETALES","ninetales-alola"),
    ("SPECIES_UXIE","uxie"), ("SPECIES_MESPRIT","mesprit"), ("SPECIES_AZELF","azelf"),
    ("SPECIES_DIALGA","dialga"), ("SPECIES_PALKIA","palkia"), ("SPECIES_HEATRAN","heatran"),
    ("SPECIES_REGIGIGAS","regigigas"), ("SPECIES_GIRATINA","giratina-altered"), ("SPECIES_CRESSELIA","cresselia"),
    ("SPECIES_PHIONE","phione"), ("SPECIES_MANAPHY","manaphy"), ("SPECIES_SHAYMIN","shaymin-land"),
    ("SPECIES_ARCEUS","arceus"),
]

# National dex numbers (164 Step-5 + 56 new)
NATIONAL_DEX = {
    "SPECIES_LUXIO":404,"SPECIES_LUXRAY":405,"SPECIES_FRAXURE":611,"SPECIES_HAXORUS":612,
    "SPECIES_DOUBLADE":680,"SPECIES_AEGISLASH":681,
    "SPECIES_GALARIAN_LINOONE":264,"SPECIES_OBSTAGOON":862,
    "SPECIES_STARLY":396,"SPECIES_STARAVIA":397,"SPECIES_STARAPTOR":398,
    "SPECIES_MUNCHLAX":446,"SPECIES_PORYGON_Z":474,
    "SPECIES_HISUIAN_ZORUA":570,"SPECIES_HISUIAN_ZOROARK":571,
    "SPECIES_FLETCHLING":661,"SPECIES_FLETCHINDER":662,"SPECIES_TALONFLAME":663,
    "SPECIES_URSALUNA":901,
    "SPECIES_SALANDIT":757,"SPECIES_SALAZZLE":758,
    "SPECIES_LITWICK":607,"SPECIES_LAMPENT":608,"SPECIES_CHANDELURE":609,
    "SPECIES_CHIMCHAR":390,"SPECIES_MONFERNO":391,"SPECIES_INFERNAPE":392,
    "SPECIES_PIPLUP":393,"SPECIES_PRINPLUP":394,"SPECIES_EMPOLEON":395,
    "SPECIES_BUIZEL":418,"SPECIES_FLOATZEL":419,
    "SPECIES_MAGMORTAR":467,"SPECIES_ELECTIVIRE":466,
    "SPECIES_ROTOM":479,"SPECIES_ROTOM_HEAT":479,"SPECIES_ROTOM_WASH":479,
    "SPECIES_ROTOM_FROST":479,"SPECIES_ROTOM_FAN":479,"SPECIES_ROTOM_MOW":479,
    "SPECIES_TOXEL":848,"SPECIES_TOXTRICITY":849,
    "SPECIES_TYNAMO":602,"SPECIES_EELEKTRIK":603,"SPECIES_EELEKTROSS":604,
    "SPECIES_ROSERADE":407,"SPECIES_TANGROWTH":465,
    "SPECIES_LEAFEON":470,"SPECIES_GLACEON":471,"SPECIES_SYLVEON":700,
    "SPECIES_FERROSEED":597,"SPECIES_FERROTHORN":598,
    "SPECIES_PUMPKABOO":710,"SPECIES_GOURGEIST":711,
    "SPECIES_PHANTUMP":708,"SPECIES_TREVENANT":709,
    "SPECIES_GALARIAN_MR_MIME":122,"SPECIES_MR_RIME":866,
    "SPECIES_MAMOSWINE":473,"SPECIES_FROSLASS":478,"SPECIES_WEAVILE":461,
    "SPECIES_GALARIAN_DARUMAKA":554,"SPECIES_GALARIAN_DARMANITAN":555,
    "SPECIES_ANNIHILAPE":979,
    "SPECIES_GALARIAN_FARFETCHD":83,"SPECIES_SIRFETCHD":865,
    "SPECIES_PANCHAM":674,"SPECIES_PANGORO":675,
    "SPECIES_CROAGUNK":453,"SPECIES_TOXICROAK":454,
    "SPECIES_RIOLU":447,"SPECIES_LUCARIO":448,
    "SPECIES_SCRAGGY":559,"SPECIES_SCRAFTY":560,
    "SPECIES_SKRELP":690,"SPECIES_DRAGALGE":691,
    "SPECIES_GIBLE":443,"SPECIES_GABITE":444,"SPECIES_GARCHOMP":445,
    "SPECIES_GLISCOR":472,"SPECIES_RHYPERIOR":464,
    "SPECIES_DRILBUR":529,"SPECIES_EXCADRILL":530,
    "SPECIES_SANDILE":551,"SPECIES_KROKOROK":552,"SPECIES_KROOKODILE":553,
    "SPECIES_GOLETT":622,"SPECIES_GOLURK":623,
    "SPECIES_HONCHKROW":430,"SPECIES_TOGEKISS":468,"SPECIES_YANMEGA":469,
    "SPECIES_HAWLUCHA":701,
    "SPECIES_ROOKIDEE":821,"SPECIES_CORVISQUIRE":822,"SPECIES_CORVIKNIGHT":823,
    "SPECIES_GALLADE":475,
    "SPECIES_INKAY":686,"SPECIES_MALAMAR":687,
    "SPECIES_LARVESTA":636,"SPECIES_VOLCARONA":637,
    "SPECIES_GRUBBIN":736,"SPECIES_CHARJABUG":737,"SPECIES_VIKAVOLT":738,
    "SPECIES_SIZZLIPEDE":850,"SPECIES_CENTISKORCH":851,
    "SPECIES_KLEAVOR":900,
    "SPECIES_HISUIAN_GROWLITHE":58,"SPECIES_HISUIAN_ARCANINE":59,
    "SPECIES_ALOLAN_GEODUDE":74,"SPECIES_ALOLAN_GRAVELER":75,"SPECIES_ALOLAN_GOLEM":76,
    "SPECIES_PROBOPASS":476,
    "SPECIES_ROCKRUFF":744,"SPECIES_LYCANROC":745,
    "SPECIES_DREEPY":885,"SPECIES_DRAKLOAK":886,"SPECIES_DRAGAPULT":887,
    "SPECIES_BASCULIN":550,"SPECIES_BASCULEGION":902,
    "SPECIES_ALOLAN_EXEGGUTOR":103,
    "SPECIES_DEINO":633,"SPECIES_ZWEILOUS":634,"SPECIES_HYDREIGON":635,
    "SPECIES_GOOMY":704,"SPECIES_SLIGGOO":705,"SPECIES_GOODRA":706,
    "SPECIES_DARKRAI":491,
    "SPECIES_ZORUA":570,"SPECIES_ZOROARK":571,
    "SPECIES_PAWNIARD":624,"SPECIES_BISHARP":625,"SPECIES_KINGAMBIT":983,
    "SPECIES_BRONZOR":436,"SPECIES_BRONZONG":437,
    "SPECIES_GALARIAN_MEOWTH":52,"SPECIES_PERRSERKER":863,
    "SPECIES_ALOLAN_MEOWTH":52,"SPECIES_ALOLAN_PERSIAN":53,
    "SPECIES_DURALUDON":884,"SPECIES_ARCHALUDON":1006,
    "SPECIES_TINKATINK":957,"SPECIES_TINKATUFF":958,"SPECIES_TINKATON":959,
    "SPECIES_ALOLAN_DIGLETT":50,"SPECIES_ALOLAN_DUGTRIO":51,
    "SPECIES_MAGNEZONE":462,
    "SPECIES_FLABEBE":669,"SPECIES_FLOETTE":670,"SPECIES_FLORGES":671,
    "SPECIES_ALOLAN_VULPIX":37,"SPECIES_ALOLAN_NINETALES":38,
    "SPECIES_UXIE":480,"SPECIES_MESPRIT":481,"SPECIES_AZELF":482,
    "SPECIES_DIALGA":483,"SPECIES_PALKIA":484,"SPECIES_HEATRAN":485,
    "SPECIES_REGIGIGAS":486,"SPECIES_GIRATINA":487,"SPECIES_CRESSELIA":488,
    "SPECIES_PHIONE":489,"SPECIES_MANAPHY":490,"SPECIES_SHAYMIN":492,
    "SPECIES_ARCEUS":493,
    # 56 new species
    "SPECIES_TEPIG":498,"SPECIES_PIGNITE":499,"SPECIES_EMBOAR":500,
    "SPECIES_FENNEKIN":653,"SPECIES_BRAIXEN":654,"SPECIES_DELPHOX":655,
    "SPECIES_LITTEN":725,"SPECIES_TORRACAT":726,"SPECIES_INCINEROAR":727,
    "SPECIES_SCORBUNNY":813,"SPECIES_RABOOT":814,"SPECIES_CINDERACE":815,
    "SPECIES_FUECOCO":909,"SPECIES_CROCALOR":910,"SPECIES_SKELEDIRGE":911,
    "SPECIES_OSHAWOTT":501,"SPECIES_DEWOTT":502,"SPECIES_SAMUROTT":503,
    "SPECIES_FROAKIE":656,"SPECIES_FROGADIER":657,"SPECIES_GRENINJA":658,
    "SPECIES_POPPLIO":728,"SPECIES_BRIONNE":729,"SPECIES_PRIMARINA":730,
    "SPECIES_SOBBLE":816,"SPECIES_DRIZZILE":817,"SPECIES_INTELEON":818,
    "SPECIES_QUAXLY":912,"SPECIES_QUAXWELL":913,"SPECIES_QUAQUAVAL":914,
    "SPECIES_TURTWIG":387,"SPECIES_GROTLE":388,"SPECIES_TORTERRA":389,
    "SPECIES_SNIVY":495,"SPECIES_SERVINE":496,"SPECIES_SERPERIOR":497,
    "SPECIES_CHESPIN":650,"SPECIES_QUILLADIN":651,"SPECIES_CHESNAUGHT":652,
    "SPECIES_ROWLET":722,"SPECIES_DARTRIX":723,"SPECIES_DECIDUEYE":724,
    "SPECIES_GROOKEY":810,"SPECIES_THWACKEY":811,"SPECIES_RILLABOOM":812,
    "SPECIES_SPRIGATITO":906,"SPECIES_FLORAGATO":907,"SPECIES_MEOWSCARADA":908,
    "SPECIES_CRANIDOS":408,"SPECIES_RAMPARDOS":409,
    "SPECIES_SHIELDON":410,"SPECIES_BASTIODON":411,
    "SPECIES_TYRUNT":696,"SPECIES_TYRANTRUM":697,
    "SPECIES_AMAURA":698,"SPECIES_AURORUS":699,
}

# 56 new species hardcoded data:
# (macro, HP,Atk,Def,SpA,SpD,Spe, t1,t2, ab1,ab2, catch,exp, body_color, gender, friends, egg_cyc, growth, eg1,eg2, ev_hp,ev_atk,ev_def,ev_spd,ev_spatk,ev_spdef)
NEW_SPECIES = [
    # Fire starters
    ("SPECIES_TEPIG",     65, 63, 45, 45, 45, 45,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45, 62,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,1,0,0,0,0),
    ("SPECIES_PIGNITE",   90, 93, 55, 70, 55, 55,"TYPE_FIRE","TYPE_FIGHTING","ABILITY_BLAZE","ABILITY_NONE",45,145,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,2,0,0,0,0),
    ("SPECIES_EMBOAR",   110,123, 65,100, 65, 65,"TYPE_FIRE","TYPE_FIGHTING","ABILITY_BLAZE","ABILITY_NONE",45,239,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    ("SPECIES_FENNEKIN",  40, 45, 40, 62, 60, 60,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45, 62,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,1,0),
    ("SPECIES_BRAIXEN",   59, 59, 58, 90, 70, 73,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45,145,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_DELPHOX",   75, 69, 72,114,100,104,"TYPE_FIRE","TYPE_PSYCHIC","ABILITY_BLAZE","ABILITY_NONE",45,239,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,3,0),
    ("SPECIES_LITTEN",    45, 65, 40, 40, 40, 70,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45, 62,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,1,0,0),
    ("SPECIES_TORRACAT",  65, 85, 50, 50, 50, 90,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45,145,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,2,0,0),
    ("SPECIES_INCINEROAR",95,115, 90, 80, 90, 60,"TYPE_FIRE","TYPE_DARK","ABILITY_INTIMIDATE","ABILITY_NONE",45,239,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    ("SPECIES_SCORBUNNY", 50, 71, 40, 40, 40, 69,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45, 62,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,1,0,0,0,0),
    ("SPECIES_RABOOT",    65, 86, 60, 55, 60, 94,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45,145,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,2,0,0),
    ("SPECIES_CINDERACE", 80,116, 75, 65, 75,119,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45,239,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,3,0,0),
    ("SPECIES_FUECOCO",   67, 45, 59, 63, 40, 36,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45, 62,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,1,0),
    ("SPECIES_CROCALOR",  81, 55, 68, 81, 50, 49,"TYPE_FIRE","TYPE_FIRE","ABILITY_BLAZE","ABILITY_NONE",45,145,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_SKELEDIRGE",104, 75,100,110, 75, 66,"TYPE_FIRE","TYPE_GHOST","ABILITY_BLAZE","ABILITY_NONE",45,239,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,0,3,0),
    # Water starters
    ("SPECIES_OSHAWOTT",  55, 55, 45, 63, 45, 45,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45, 62,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,1,0),
    ("SPECIES_DEWOTT",    75, 75, 60, 83, 60, 60,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,145,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_SAMUROTT",  95,100, 85,108, 70, 70,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,239,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,3,0),
    ("SPECIES_FROAKIE",   41, 56, 40, 62, 44, 71,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45, 62,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,1,0,0),
    ("SPECIES_FROGADIER", 54, 63, 52, 83, 56, 97,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,145,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,2,0,0),
    ("SPECIES_GRENINJA",  72, 95, 67,103, 71,122,"TYPE_WATER","TYPE_DARK","ABILITY_TORRENT","ABILITY_NONE",45,239,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,3,0,0),
    ("SPECIES_POPPLIO",   50, 54, 54, 66, 56, 40,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45, 62,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,1,0),
    ("SPECIES_BRIONNE",   60, 69, 69, 91, 81, 50,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,145,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_PRIMARINA", 80, 74, 74,126,116, 60,"TYPE_WATER","TYPE_FAIRY","ABILITY_TORRENT","ABILITY_NONE",45,239,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,3,0),
    ("SPECIES_SOBBLE",    50, 40, 40, 70, 40, 70,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45, 62,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,1,0),
    ("SPECIES_DRIZZILE",  65, 60, 55, 95, 55, 90,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,145,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_INTELEON",  70, 85, 65,125, 65,120,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,239,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,0,0,0,3,0),
    ("SPECIES_QUAXLY",    55, 65, 45, 45, 45, 50,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45, 62,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,1,0,0,0,0),
    ("SPECIES_QUAXWELL",  70, 78, 60, 58, 60, 65,"TYPE_WATER","TYPE_WATER","ABILITY_TORRENT","ABILITY_NONE",45,145,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,2,0,0,0,0),
    ("SPECIES_QUAQUAVAL", 85,120, 80, 85, 75, 85,"TYPE_WATER","TYPE_FIGHTING","ABILITY_TORRENT","ABILITY_NONE",45,239,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_WATER_1","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    # Grass starters
    ("SPECIES_TURTWIG",   55, 68, 64, 45, 55, 31,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45, 64,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,1,0,0,0),
    ("SPECIES_GROTLE",    75, 89, 85, 55, 65, 36,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,142,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,2,0,0,0),
    ("SPECIES_TORTERRA",  95,109,105, 75, 85, 56,"TYPE_GRASS","TYPE_GROUND","ABILITY_OVERGROW","ABILITY_NONE",45,239,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,3,0,0,0),
    ("SPECIES_SNIVY",     45, 45, 55, 45, 55, 63,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45, 62,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,1,0,0),
    ("SPECIES_SERVINE",   60, 60, 75, 60, 75, 83,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,145,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,2,0,0),
    ("SPECIES_SERPERIOR", 75, 75, 95, 75, 95,113,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,238,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,3,0,0),
    ("SPECIES_CHESPIN",   56, 61, 65, 48, 45, 38,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45, 63,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,1,0,0,0),
    ("SPECIES_QUILLADIN", 61, 78, 95, 56, 58, 57,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,142,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,2,0,0,0),
    ("SPECIES_CHESNAUGHT",88,107,122, 74, 75, 64,"TYPE_GRASS","TYPE_FIGHTING","ABILITY_OVERGROW","ABILITY_NONE",45,239,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,3,0,0,0),
    ("SPECIES_ROWLET",    68, 55, 55, 50, 50, 42,"TYPE_GRASS","TYPE_FLYING","ABILITY_OVERGROW","ABILITY_NONE",45, 64,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FLYING","EGG_GROUP_FIELD", 1,0,0,0,0,0),
    ("SPECIES_DARTRIX",   78, 75, 75, 70, 70, 52,"TYPE_GRASS","TYPE_FLYING","ABILITY_OVERGROW","ABILITY_NONE",45,147,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FLYING","EGG_GROUP_FIELD", 2,0,0,0,0,0),
    ("SPECIES_DECIDUEYE", 78,107, 75,100,100, 70,"TYPE_GRASS","TYPE_GHOST","ABILITY_OVERGROW","ABILITY_NONE",45,239,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FLYING","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    ("SPECIES_GROOKEY",   50, 65, 50, 40, 40, 65,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45, 62,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,1,0,0,0,0),
    ("SPECIES_THWACKEY",  70, 85, 70, 55, 60, 80,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,145,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,2,0,0,0,0),
    ("SPECIES_RILLABOOM", 100,125, 90, 60, 70, 85,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,255,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    ("SPECIES_SPRIGATITO", 40, 61, 54, 45, 45, 65,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45, 62,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,1,0,0),
    ("SPECIES_FLORAGATO",  61, 80, 63, 60, 63, 83,"TYPE_GRASS","TYPE_GRASS","ABILITY_OVERGROW","ABILITY_NONE",45,145,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,2,0,0),
    ("SPECIES_MEOWSCARADA",76,110, 70, 81, 70,123,"TYPE_GRASS","TYPE_DARK","ABILITY_OVERGROW","ABILITY_NONE",45,255,"BODY_COLOR_GREEN","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_FIELD","EGG_GROUP_FIELD", 0,0,0,3,0,0),
    # Rock fossils
    ("SPECIES_CRANIDOS",  67,125, 40, 30, 30, 58,"TYPE_ROCK","TYPE_ROCK","ABILITY_ROCK_HEAD","ABILITY_NONE",45, 70,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,2,0,0,0,0),
    ("SPECIES_RAMPARDOS", 97,165, 60, 65, 50, 58,"TYPE_ROCK","TYPE_ROCK","ABILITY_ROCK_HEAD","ABILITY_NONE",45,173,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,3,0,0,0,0),
    ("SPECIES_SHIELDON",  30, 42,118, 42, 88, 30,"TYPE_ROCK","TYPE_STEEL","ABILITY_STURDY","ABILITY_NONE",45, 70,"BODY_COLOR_GRAY","PERCENT_FEMALE(50)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,0,2,0,0,0),
    ("SPECIES_BASTIODON", 60, 52,168, 47,138, 30,"TYPE_ROCK","TYPE_STEEL","ABILITY_STURDY","ABILITY_NONE",45,173,"BODY_COLOR_GRAY","PERCENT_FEMALE(50)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,0,3,0,0,0),
    ("SPECIES_TYRUNT",    58, 89, 77, 45, 45, 48,"TYPE_ROCK","TYPE_DRAGON","ABILITY_HUSTLE","ABILITY_NONE",45, 72,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_DRAGON", 0,2,0,0,0,0),
    ("SPECIES_TYRANTRUM", 82,121,119, 69, 59, 71,"TYPE_ROCK","TYPE_DRAGON","ABILITY_HUSTLE","ABILITY_NONE",45,172,"BODY_COLOR_RED","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_DRAGON", 0,3,0,0,0,0),
    ("SPECIES_AMAURA",    77, 59, 50, 67, 63, 46,"TYPE_ROCK","TYPE_ICE","ABILITY_OBLIVIOUS","ABILITY_NONE",45, 72,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,0,0,0,2,0),
    ("SPECIES_AURORUS",  123, 77, 72, 99, 92, 58,"TYPE_ROCK","TYPE_ICE","ABILITY_OBLIVIOUS","ABILITY_NONE",45,173,"BODY_COLOR_BLUE","PERCENT_FEMALE(12)",70,20,"GROWTH_MEDIUM_SLOW","EGG_GROUP_MONSTER","EGG_GROUP_FIELD", 0,0,0,0,3,0),
]

# EGG_GROUP defaults based on primary type
EGG_GROUP_BY_TYPE = {
    "TYPE_GHOST": "EGG_GROUP_AMORPHOUS",
    "TYPE_BUG":   "EGG_GROUP_BUG",
    "TYPE_FAIRY": "EGG_GROUP_FAIRY",
    "TYPE_DRAGON":"EGG_GROUP_DRAGON",
    "TYPE_WATER": "EGG_GROUP_WATER_1",
    "TYPE_FLYING":"EGG_GROUP_FLYING",
}

LEGENDARY_EXP = {261,270,302,306,324}  # exp yields that indicate legendary

def get_egg_groups(type1, exp_yield):
    if exp_yield in LEGENDARY_EXP or exp_yield >= 300:
        return "EGG_GROUP_UNDISCOVERED", "EGG_GROUP_UNDISCOVERED"
    eg = EGG_GROUP_BY_TYPE.get(type1, "EGG_GROUP_FIELD")
    return eg, eg


def load_csvs():
    # pokemon.csv: id,identifier,species_id,height,weight,base_experience,...
    pmon = {}
    with open(f"{CACHE}/pokemon.csv") as f:
        for row in csv.DictReader(f):
            pmon[row["identifier"]] = {
                "id": int(row["id"]),
                "species_id": int(row["species_id"]),
                "base_exp": int(row["base_experience"]) if row["base_experience"] else 100,
            }

    # pokemon_stats.csv: pokemon_id,stat_id,base_stat,effort
    stats = {}
    with open(f"{CACHE}/pokemon_stats.csv") as f:
        for row in csv.DictReader(f):
            pid = int(row["pokemon_id"])
            if pid not in stats:
                stats[pid] = {}
            stats[pid][int(row["stat_id"])] = int(row["base_stat"])

    # pokemon_types.csv: pokemon_id,type_id,slot
    types = {}
    with open(f"{CACHE}/pokemon_types.csv") as f:
        for row in csv.DictReader(f):
            pid = int(row["pokemon_id"])
            if pid not in types:
                types[pid] = []
            types[pid].append(int(row["type_id"]))

    # pokemon_species.csv: id,...,gender_rate,capture_rate,base_happiness,...,hatch_counter,...,growth_rate_id,...
    species = {}
    with open(f"{CACHE}/pokemon_species.csv") as f:
        for row in csv.DictReader(f):
            species[int(row["id"])] = {
                "gender_rate": int(row["gender_rate"]),
                "capture_rate": int(row["capture_rate"]),
                "base_happiness": int(row["base_happiness"]),
                "hatch_counter": int(row["hatch_counter"]),
                "growth_rate_id": int(row["growth_rate_id"]),
            }

    return pmon, stats, types, species


def make_entry(macro, HP, Atk, Def, SpA, SpD, Spe,
               t1, t2, ab1, ab2, catch, exp,
               body_color, gender, friends, egg_cyc, growth,
               eg1, eg2, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef):
    exp = min(exp, 255)
    return (
        f"    [{macro}] =\n"
        f"    {{\n"
        f"        .baseHP = {HP},\n"
        f"        .baseAttack = {Atk},\n"
        f"        .baseDefense = {Def},\n"
        f"        .baseSpeed = {Spe},\n"
        f"        .baseSpAttack = {SpA},\n"
        f"        .baseSpDefense = {SpD},\n"
        f"        .types = {{{t1}, {t2}}},\n"
        f"        .catchRate = {catch},\n"
        f"        .expYield = {exp},\n"
        f"        .evYield_HP = {ev_hp},\n"
        f"        .evYield_Attack = {ev_atk},\n"
        f"        .evYield_Defense = {ev_def},\n"
        f"        .evYield_Speed = {ev_spd},\n"
        f"        .evYield_SpAttack = {ev_spatk},\n"
        f"        .evYield_SpDefense = {ev_spdef},\n"
        f"        .itemCommon = ITEM_NONE,\n"
        f"        .itemRare = ITEM_NONE,\n"
        f"        .genderRatio = {gender},\n"
        f"        .eggCycles = {egg_cyc},\n"
        f"        .friendship = {friends},\n"
        f"        .growthRate = {growth},\n"
        f"        .eggGroups = {{{eg1}, {eg2}}},\n"
        f"        .abilities = {{{ab1}, {ab2}}},\n"
        f"        .safariZoneFleeRate = 0,\n"
        f"        .bodyColor = {body_color},\n"
        f"        .noFlip = FALSE,\n"
        f"    }},\n\n"
    )


NAME_OVERRIDES = {
    "SPECIES_PORYGON_Z":          "PORYGON-Z",
    "SPECIES_ROTOM_HEAT":         "ROTOM-HEAT",
    "SPECIES_ROTOM_WASH":         "ROTOM-WASH",
    "SPECIES_ROTOM_FROST":        "ROTOM-FRST",
    "SPECIES_ROTOM_FAN":          "ROTOM-FAN",
    "SPECIES_ROTOM_MOW":          "ROTOM-MOW",
    "SPECIES_GALARIAN_LINOONE":   "G-LINOONE",
    "SPECIES_GALARIAN_MR_MIME":   "G-MR.MIME",
    "SPECIES_GALARIAN_DARUMAKA":  "G-DARUMAKA",
    "SPECIES_GALARIAN_DARMANITAN":"G-DARMANTN",
    "SPECIES_GALARIAN_FARFETCHD": "G-FARFTCHD",
    "SPECIES_GALARIAN_MEOWTH":    "G-MEOWTH",
    "SPECIES_HISUIAN_ZORUA":      "H-ZORUA",
    "SPECIES_HISUIAN_ZOROARK":    "H-ZOROARK",
    "SPECIES_HISUIAN_GROWLITHE":  "H-GROWLITE",
    "SPECIES_HISUIAN_ARCANINE":   "H-ARCANINE",
    "SPECIES_ALOLAN_GEODUDE":     "A-GEODUDE",
    "SPECIES_ALOLAN_GRAVELER":    "A-GRAVELER",
    "SPECIES_ALOLAN_GOLEM":       "A-GOLEM",
    "SPECIES_ALOLAN_EXEGGUTOR":   "A-EXEGUTOR",
    "SPECIES_ALOLAN_MEOWTH":      "A-MEOWTH",
    "SPECIES_ALOLAN_PERSIAN":     "A-PERSIAN",
    "SPECIES_ALOLAN_DIGLETT":     "A-DIGLETT",
    "SPECIES_ALOLAN_DUGTRIO":     "A-DUGTRIO",
    "SPECIES_ALOLAN_VULPIX":      "A-VULPIX",
    "SPECIES_ALOLAN_NINETALES":   "A-NINETALS",
    "SPECIES_FLETCHINDER":        "FLETCHINDR",
    "SPECIES_BASCULEGION":        "BASCULEGON",
    "SPECIES_CENTISKORCH":        "CENTISKORC",
    "SPECIES_MEOWSCARADA":        "MEOWSCARDA",
}

def macro_to_name(macro):
    if macro in NAME_OVERRIDES:
        return NAME_OVERRIDES[macro]
    name = macro[8:]  # strip "SPECIES_"
    name = name.replace("_", " ")
    return name[:10]


def main():
    os.makedirs("build", exist_ok=True)

    print("Loading CSVs...")
    pmon, stats, types_csv, species_csv = load_csvs()

    # ── step5_species_info.inc ──────────────────────────────────────
    out = ["// Generated by tools/gen_step5_species_inc.py\n// DO NOT EDIT — regenerate with: python3 tools/gen_step5_species_inc.py\n\n"]

    for macro, ident in SPECIES_LIST:
        if ident not in pmon:
            print(f"  WARNING: {ident} not found in CSV, using fallback defaults for {macro}")
            entry = make_entry(macro, 70,70,70,70,70,70,
                "TYPE_NORMAL","TYPE_NORMAL","ABILITY_NONE","ABILITY_NONE",
                45,100,"BODY_COLOR_GRAY","PERCENT_FEMALE(50)",70,20,
                "GROWTH_MEDIUM_FAST","EGG_GROUP_FIELD","EGG_GROUP_FIELD",
                0,0,0,0,1,0)
            out.append(entry)
            continue

        pm = pmon[ident]
        pid = pm["id"]
        sid = pm["species_id"]

        s = stats.get(pid, {})
        HP  = s.get(1, 70)
        Atk = s.get(2, 70)
        Def = s.get(3, 70)
        SpA = s.get(4, 70)
        SpD = s.get(5, 70)
        Spe = s.get(6, 70)

        t_ids = types_csv.get(pid, [1])
        t1 = TYPE_MAP.get(t_ids[0], "TYPE_NORMAL")
        t2 = TYPE_MAP.get(t_ids[1] if len(t_ids) > 1 else t_ids[0], t1)

        sp = species_csv.get(sid, {})
        catch   = sp.get("capture_rate", 45)
        friends = sp.get("base_happiness", 70)
        egg_cyc = sp.get("hatch_counter", 20)
        gr_id   = sp.get("growth_rate_id", 4)
        growth  = GROWTH_MAP.get(gr_id, "GROWTH_MEDIUM_SLOW")
        g_rate  = sp.get("gender_rate", 4)
        gender  = GENDER_MAP.get(g_rate, "PERCENT_FEMALE(50)")

        # Get corrections
        corr = CORRECTIONS.get(macro)
        if corr:
            ab1, ab2, body_color, exp, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef = corr
        else:
            print(f"  WARNING: No corrections for {macro}, using defaults")
            exp = min(pm["base_exp"], 255)
            ab1, ab2 = "ABILITY_NONE", "ABILITY_NONE"
            body_color = "BODY_COLOR_GRAY"
            ev_hp = ev_atk = ev_def = ev_spd = ev_spatk = ev_spdef = 0

        exp = min(exp, 255)

        eg1, eg2 = get_egg_groups(t1, exp)

        out.append(make_entry(macro, HP, Atk, Def, SpA, SpD, Spe,
            t1, t2, ab1, ab2, catch, exp, body_color, gender, friends, egg_cyc, growth,
            eg1, eg2, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef))

    out.append("    // === 56 new species (Gen 5-9 starters + fossils) ===\n\n")
    for row in NEW_SPECIES:
        (macro, HP, Atk, Def, SpA, SpD, Spe, t1, t2, ab1, ab2,
         catch, exp, body_color, gender, friends, egg_cyc, growth,
         eg1, eg2, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef) = row
        out.append(make_entry(macro, HP, Atk, Def, SpA, SpD, Spe,
            t1, t2, ab1, ab2, catch, exp, body_color, gender, friends, egg_cyc, growth,
            eg1, eg2, ev_hp, ev_atk, ev_def, ev_spd, ev_spatk, ev_spdef))

    with open("build/step5_species_info.inc", "w") as f:
        f.writelines(out)
    print(f"Wrote build/step5_species_info.inc ({len(SPECIES_LIST)+len(NEW_SPECIES)} species)")

    # Pre-step5 species that also need national dex + species_to_national entries
    # (Shinx/Axew/Honedge added before step5; Galarian Zigzagoon shares dex 263)
    PRE_STEP5 = {
        "SPECIES_SHINX":              403,
        "SPECIES_AXEW":               610,
        "SPECIES_HONEDGE":            679,
        "SPECIES_GALARIAN_ZIGZAGOON": 263,
    }

    # ── step5_national_dex.inc ──────────────────────────────────────
    dex_lines = ["// Generated by tools/gen_step5_species_inc.py\n\n"]
    for macro, num in NATIONAL_DEX.items():
        dex_name = macro.replace("SPECIES_", "NATIONAL_DEX_")
        dex_lines.append(f"    {dex_name} = {num},\n")
    for macro, num in PRE_STEP5.items():
        dex_name = macro.replace("SPECIES_", "NATIONAL_DEX_")
        dex_lines.append(f"    {dex_name} = {num},\n")

    with open("build/step5_national_dex.inc", "w") as f:
        f.writelines(dex_lines)
    print(f"Wrote build/step5_national_dex.inc ({len(NATIONAL_DEX)+len(PRE_STEP5)} entries)")

    # ── step5_species_names.inc ──────────────────────────────────────
    names_lines = ["// Generated by tools/gen_step5_species_inc.py\n\n"]
    for macro, ident in SPECIES_LIST:
        display = macro_to_name(macro)
        names_lines.append(f'    [{macro}] = _("{display}"),\n')
    for row in NEW_SPECIES:
        macro = row[0]
        display = macro_to_name(macro)
        names_lines.append(f'    [{macro}] = _("{display}"),\n')
    with open("build/step5_species_names.inc", "w") as f:
        f.writelines(names_lines)
    print(f"Wrote build/step5_species_names.inc ({len(SPECIES_LIST)+len(NEW_SPECIES)} entries)")

    # ── step5_species_to_national.inc ──────────────────────────────────────
    nat_lines = ["// Generated by tools/gen_step5_species_inc.py\n\n"]
    for macro in NATIONAL_DEX:
        short = macro[8:]  # strip "SPECIES_"
        nat_lines.append(f"    SPECIES_TO_NATIONAL({short}),\n")
    for macro in PRE_STEP5:
        short = macro[8:]
        nat_lines.append(f"    SPECIES_TO_NATIONAL({short}),\n")
    with open("build/step5_species_to_national.inc", "w") as f:
        f.writelines(nat_lines)
    print(f"Wrote build/step5_species_to_national.inc ({len(NATIONAL_DEX)+len(PRE_STEP5)} entries)")


if __name__ == "__main__":
    main()
